# Generated by Django 5.1.5 on 2025-01-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.Uj-WLdfpgM4fBj8dhWe5VAHaHd?w=197&h=199&c=7&r=0&o=5&pid=1.7', max_length=500),
        ),
    ]
