# Generated by Django 5.1.5 on 2025-01-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobbies_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolio_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.Uj-WLdfpgM4fBj8dhWe5VAHaHd?w=197&h=199&c=7&r=0&o=5&pid=1.7', max_length=500),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hobby_years',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
