# Generated by Django 5.1.5 on 2025-01-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_portfoliomodel_portfolio_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='portfolio_created',
            field=models.CharField(default='January, 2025', max_length=100),
        ),
    ]
